name: Full Build STM32 Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build the Docker Image
        run: echo "$ACTIONS_ID_TOKEN_REQUEST_URL" | grep -Po 'https://[^/]+/[^/]+/' | sed  's/pipelines/artifactcache/' > $ACTIONS_CACHE_URL \
             echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN > $ACTIONS_RUNTIME_TOKEN \
             docker buildx build --load -t stm32-workspace . -f docker/toolchain.dockerfile 

      - name: Test Build STM32 Flash Image
        run: docker run -v $(pwd):/opt/project -i --rm --hostname stm32-workspace --workdir /opt/project stm32-workspace:latest ./build.sh
